# Generated by Django 4.2.10 on 2024-02-11 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('dateOfBirth', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
            ],
            options={
                'db_table': 'Начальник',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name', models.CharField(help_text='Введите название отдела', max_length=100, primary_key=True, serialize=False, verbose_name='Название отдела')),
                ('description', models.TextField(verbose_name='Описание отдела')),
            ],
            options={
                'db_table': 'Отдел',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название группы', max_length=100, verbose_name='Название группы')),
            ],
            options={
                'db_table': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('focus_name', models.CharField(help_text='Введите название направленности', max_length=100, primary_key=True, serialize=False, verbose_name='Направленность')),
                ('boss', models.ForeignKey(help_text='Выберите начальника', on_delete=django.db.models.deletion.CASCADE, to='test_django.boss', verbose_name='Начальник')),
                ('groups', models.ManyToManyField(to='test_django.group')),
            ],
            options={
                'db_table': 'Направленность',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя', max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('dateOfBirth', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('group', models.ForeignKey(help_text='Выберите группу', on_delete=django.db.models.deletion.CASCADE, to='test_django.group', verbose_name='Группа')),
                ('id_user', models.ForeignKey(blank=True, help_text='Введите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя')),
            ],
            options={
                'db_table': 'Сотрудник',
            },
        ),
        migrations.AddField(
            model_name='boss',
            name='division',
            field=models.ForeignKey(help_text='Выберите компанию', on_delete=django.db.models.deletion.CASCADE, to='test_django.division', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='boss',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='Введите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Введите номер задачи', verbose_name='Номер задачи')),
                ('salary', models.IntegerField(help_text='Введите размер зарплаты', verbose_name='Зарплата')),
                ('date_control', models.DateField(help_text='Введите дату сдачи проекта', verbose_name='Дата сдачи проекта')),
                ('employee', models.ForeignKey(help_text='Выберите сотрудника', on_delete=django.db.models.deletion.CASCADE, to='test_django.employee', verbose_name='Сотрудник')),
                ('focus', models.ForeignKey(help_text='Выберите направленность', on_delete=django.db.models.deletion.CASCADE, to='test_django.focus', verbose_name='Направленность')),
            ],
            options={
                'db_table': 'Рабочие задачи',
            },
        ),
    ]
